spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/course_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.zjsu.syt.course: INFO